name: python-checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu:latest
    steps:
      - name: clone git repository
        uses: actions/checkout@v4

      - name: run black
        run: black . --check

      - name: run mypy
        run: mypy .

      - name: run ruff
        run: ruff check

