from dataclasses import dataclass

USER_SURNAME_MIN_LENGTH = 3
USER_SURNAME_MAX_LENGTH = 20

USER_NAME_MIN_LENGTH = 3
USER_NAME_MAX_LENGTH = 25

USER_USERNAME_MIN_LENGTH = 5
USER_USERNAME_MAX_LENGTH = 20

USER_EMAIL_MIN_LENGTH = 5
USER_EMAIL_MAX_LENGTH = 30

USER_ENCRYPTED_PASSWORD_MAX_LENGTH = 128


FILE_BUCKET_LENGTH = 25
FILE_KEY_LENGTH = 40


@dataclass
class S3Bucket:
    input_bucket = "input"
    output_bucket = "output"


s3_bucket = S3Bucket()
